// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAolC77TKG0PBBUSH7DIi9Q7IpEd0_1hd8',
    appId: '1:115199002040:web:7270d2c8bd9612d5ecbb4d',
    messagingSenderId: '115199002040',
    projectId: 'musicapp-2af3f',
    authDomain: 'musicapp-2af3f.firebaseapp.com',
    databaseURL: 'https://musicapp-2af3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-2af3f.firebasestorage.app',
    measurementId: 'G-MZ2NTDFDQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh3fi-YBWF2hsgWbJBIp6ks-K_p3DGERQ',
    appId: '1:115199002040:android:e5d47abe4c5504ccecbb4d',
    messagingSenderId: '115199002040',
    projectId: 'musicapp-2af3f',
    databaseURL: 'https://musicapp-2af3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-2af3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7_7ZOB1C-9vJhw2Oj2RFIbkwWHqLgBk',
    appId: '1:115199002040:ios:02ab4c543efbb786ecbb4d',
    messagingSenderId: '115199002040',
    projectId: 'musicapp-2af3f',
    databaseURL: 'https://musicapp-2af3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-2af3f.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAolC77TKG0PBBUSH7DIi9Q7IpEd0_1hd8',
    appId: '1:115199002040:web:682ba45379fecdffecbb4d',
    messagingSenderId: '115199002040',
    projectId: 'musicapp-2af3f',
    authDomain: 'musicapp-2af3f.firebaseapp.com',
    databaseURL: 'https://musicapp-2af3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-2af3f.firebasestorage.app',
    measurementId: 'G-YRQBC1H06C',
  );

}